config/routes.rb
TrelloClone::Application.routes.draw do
  root to: 'static_pages#root'

  resources :users
  resource :session

  namespace :api, defaults: { format: :json } do
    resources :boards, except: [:new, :edit]
    resources :lists, only: [:create, :update, :destroy]
    resources :cards, only: [:create, :update, :destroy]

    # resources :items
    # resources :board_memberships
    # resources :card_assignments
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Trello Clone</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
    <% if signed_in? %>
      <li id='add-dropdown' class='dropdown'>
        <button
          class='dropdown-toggle navbar-btn btn btn-primary'
          data-toggle='dropdown'><span class='glyphicon glyphicon-plus'></span>
        </button>
      </li>
      <li><%= button_to "Sign out", session_url, method: :delete, class: "btn btn-primary navbar-btn" %></li>
    <% else %>
      <li><%= link_to "Log in", new_session_url %></li>
      <li><%= link_to "Sign up", new_user_url %></li>
    <% end %>
    </ul>
  </div>
</div>
</nav>

<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trello Clone</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/header" %>
  <%= yield %>
</body>
</html>